name: Twitter weather bot

on:
  schedule:
    - cron: "0 */6 * * *"
  workflow_dispatch:

jobs:
  run_crawler:
    runs-on: ubuntu-latest
    env: 
      consumer_key: ${{secrets.API_KEY}}
      consumer_secret: ${{secrets.API_KEY_SECRET}}
      access_token: ${{secrets.ACCESS_TOKEN}}
      access_token_secret: ${{secrets.ACCESS_TOKEN_SECRET}}
      serviceKey: ${{secrets.SERVICEKEY}}
      fcst_x: ${{secrets.FCST_X}}
      fcst_y: ${{secrets.FCST_Y}}
      api_url: ${{secrets.API_URL}}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v3
      - run: pip install tweepy pytz
      - run: python main.py
